spring:
  shell:
    interactive:
      enabled: true

  data:
    mongodb:
      uri: mongodb://localhost
      port: 27017
      database: app_db
      changelogs: com.mycompany.hw_l13_spring_data_nosql.changelogs

  logging:
    level:
      root: ERROR

