spring:
  thymeleaf:
    prefix: classpath:/static/

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    initialization-mode: always
    data: classpath:/data.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate

    show-sql: true
    properties:
      hibernate:
        format_sql: true

hystrix:
  command:
    library:
      circuitBreaker.requestVolumeThreshold: 10
      execution.isolation.thread.timeoutInMilliseconds: 5000