spring:
  shell:
    interactive:
      enabled: true

  datasource:
    url: jdbc:h2:mem:app_rdb
    driver-class-name: org.h2.Driver
    initialization-mode: always
    data: classpath:/data.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
