spring:
  thymeleaf:
    prefix: classpath:/static/

  data:
    mongodb:
      uri: mongodb://localhost
      port: 0
      database: app_db
      changelogs: com.mycompany.hw_l20_spring_webflux.changelogs

  logging:
    level:
      root: ERROR