version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/app_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DRIVER=org.postgresql.Driver
    depends_on:
      - postgres

  postgres:
    image: "postgres:12-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    volumes:
      - app_db_data:/var/lib/postgresql/data

  volumes:
    app_db_data:


