DROP TABLE IF EXISTS PERSONS;
CREATE TABLE BOOKS(
    ID BIGINT PRIMARY KEY,
    TITLE VARCHAR(255),
    AUTHOR_ID BIGINT FOREIGN KEY REFERENCES AUTHORS(ID),
    GENRE_ID BIGINT FOREIGN KEY REFERENCES GENRES(ID)
);

DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255),
    SURNAME VARCHAR(255),
    BOOK_ID BIGINT FOREIGN KEY REFERENCES BOOKS(ID)
);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255),
    BOOK_ID BIGINT FOREIGN KEY REFERENCES BOOKS(ID)
);